refactor(update-status script): :hammer: Simplify VPC ID retrieval by commenting out unused code and adjusting variable initialization

diff --git a/promise-vpc-hcp/internal/configure-pipeline/update-status b/promise-vpc-hcp/internal/configure-pipeline/update-status
--- a/promise-vpc-hcp/internal/configure-pipeline/update-status
+++ b/promise-vpc-hcp/internal/configure-pipeline/update-status
@@ -4,25 +4,25 @@ echo "🟢 Running update-status script..."
 
 name=$(yq '.metadata.name' /kratix/input/object.yaml)
 region="us-east-1"
+vpc_id="debug"
+# # Get VPC ID based on tag "Name"
+# vpc_id=$(aws ec2 describe-vpcs \
+#   --region "$region" \
+#   --filters "Name=tag:Name,Values=$name" \
+#   --query "Vpcs[0].VpcId" \
+#   --output text)
 
-# Get VPC ID based on tag "Name"
-vpc_id=$(aws ec2 describe-vpcs \
-  --region "$region" \
-  --filters "Name=tag:Name,Values=$name" \
-  --query "Vpcs[0].VpcId" \
-  --output text)
-
-# Check for valid result
-sleep 30
-if [ "$vpc_id" = "None" ]; then
-  echo "❌ VPC not found with Name tag: $name"
-  exit 1
-fi
+# # Check for valid result
+# sleep 30
+# if [ "$vpc_id" = "None" ]; then
+#   echo "❌ VPC not found with Name tag: $name"
+#   exit 1
+# fi
 
 # Create status.yaml to mark the resource ready
 cat <<EOF > /kratix/metadata/status.yaml
 ready: "True"
-vpcId: "$vpc_id"
+# vpcId: "$vpc_id"
 vpcName: "$name"
 EOF
 
